version: '3.1'

services:
  nginx:
    image: nginx:latest
    container_name: websocket-ssl-sample-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/server_key.pem:/etc/nginx/server_key.pem
      - ./nginx/server_crt.pem:/etc/nginx/server_crt.pem
      - ./htdocs:/usr/share/nginx/html
    ports:
      - "10443:443"
    environment:
      TZ: Asia/Tokyo

  app:
    build: .
    container_name: websocket-ssl-sample-app
    ports:
      - "3000"
